version: "3.3"

services:
  nginx:
    image: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${PWD}/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ${PWD}/nginx/njs:/etc/nginx/njs
      - ${PWD}/nginx/templates:/etc/nginx/templates
      - ${PWD}/ssl:/etc/ssl/nginx
      - ${PWD}/logs:/var/log/nginx
    environment:
      - PRISM_HOST=${PRISM_HOST}
      - PRISM_PORT=${PRISM_PORT}